### ISSUE TITLE
Does not send the text/file to multiple google home devices

### ISSUE THREAD

**Issue by skarotech** [watusi/google-cast-public-address#19]
Hi,

I have this running, and it picks up both of my Home devices, and the first time I send something via the POST command, it sends to both, but subsequent POST's only work to one of the Home devices.

Is this a bug, or a settings issue ?
![screen shot 2017-09-03 at 4 29 52 pm](https://user-images.githubusercontent.com/29419003/30001043-2810fb1e-90c5-11e7-9985-4f23fbc40c2a.png)

**Comment by jtara** [comment]
Thanks for bringing this to my attention. I had THOUGHT I had fixed this! Somehow, I closed the previous issue #15, and the issue detailing the implementation needed to fix it #16.

As this is a duplicate, closing this issue. I will try to address this in the near future. If you have further comments, please add to #15, although none needed as I understand what causes this. Feel free to add comments to #15, #16 once I push new code.
